# Generated by Django 3.0.8 on 2020-07-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrativeprocedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeProcedures',
            fields=[
                ('id_administrativeprocedures', models.AutoField(primary_key=True, serialize=False)),
                ('denomination', models.CharField(max_length=100, unique=True)),
                ('code_bankn', models.CharField(max_length=10, unique=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'administrative_procedures',
            },
        ),
        migrations.CreateModel(
            name='UniversityFaculty',
            fields=[
                ('id_universtityfaculty', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administrativeprocedures.Unit')),
            ],
            options={
                'db_table': 'university_faculty',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeProceduresRequest',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('administration_procedures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administrativeprocedures.AdministrativeProcedures')),
            ],
            options={
                'db_table': 'administrative_procedures_request',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeProceduresDenominationGlobal',
            fields=[
                ('id_denominationglobal', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administrativeprocedures.Unit')),
            ],
            options={
                'db_table': 'administrative_procedures_denomination_global',
            },
        ),
        migrations.AddField(
            model_name='administrativeprocedures',
            name='denomination_global',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administrativeprocedures.AdministrativeProceduresDenominationGlobal'),
        ),
    ]
