# Generated by Django 3.0.8 on 2020-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrativeprocedures', '0002_auto_20200726_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeproceduresdenominationglobal',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='administrativeproceduresrequest',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
