# Generated by Django 3.0.8 on 2020-07-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrativeprocedures', '0003_auto_20200726_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativeprocedures',
            old_name='code_bankn',
            new_name='code_bank',
        ),
    ]
