# Generated by Django 3.0.8 on 2020-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrativeprocedures', '0004_auto_20200726_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprocedures',
            name='code_bank',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativeprocedures',
            name='denomination',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
