# Generated by Django 3.0.8 on 2020-07-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrativeprocedures', '0005_auto_20200726_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeproceduresrequest',
            name='code_bank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='administrativeproceduresrequest',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
