# Generated by Django 3.0.8 on 2020-07-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrativeprocedures', '0006_auto_20200726_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprocedures',
            name='denomination',
            field=models.CharField(max_length=200),
        ),
    ]
